### ISSUE TITLE
Questions et Suggestions

### ISSUE THREAD

**Issue by xekil** [psykokwak-com/everblu-meters-esp8266#2]
Bonjour et merci une nouvelle fois pour ce projet :)

J'aurais quelques questions et suggestions concernant le fonctionnement :

Avec la dernière version (OTA), j'ai remarqué que l'interrogation du compteur s'effectue à 12:00, et qu'elle ne s'effectue plus lors de la mise en route de l'ESP ou du flash, il est donc nécessaire d'adapter la zone de temps en fonction de notre pays.

**Lors du test de fréquence, j'ai obtenu 433.861681, la lecture serait elle plus fiable avec :**

- 433.8616 ou 433.8616**8** ou 433.8616**81** ?

  Avec 433.8616 ça semble fonctionner correctement mais je vais pas encore assez de recul.

**Est-il possible de rajouter des capteurs MQTT pour Home Assistant :**

- La possibilité d'effectuer une relève manuellement ([peut être via MQTT Button](https://www.home-assistant.io/integrations/button.mqtt/))
- Puissance du signal Wi-Fi ([MQTT Sensor](https://www.home-assistant.io/integrations/sensor.mqtt/))
- État de la connexion ([MQTT Binary Sensor](https://www.home-assistant.io/integrations/binary_sensor.mqtt/))
- Disponibilité de l'ESP (Capteur Uptime)
- Reboot de l'ESP (Switch ou Bouton)

Enfin, avoir un accès au Debug en WIFI serait vraiment bien, j'ai trouvé quelques projets intéressants.

**Terminal via client Telnet**

- https://forum.arduino.cc/t/serveur-telnet-pour-esp8266/656597
- https://www.fais-le-toi-meme.fr/fr/electronique/tutoriel/esp8266-arduinoota-mise-a-jour-logiciel-esp8266-wifi
- https://github.com/JoaoLopesF/RemoteDebug

**Terminal Http**

- https://forum.arduino.cc/t/terminal-wifi-pour-esp/640110
- https://forum.arduino.cc/t/terminal-wifi-pour-esp8266-esp32/643876

PS : J'écris en français car il semble que nous soyons majoritairement des français à utiliser ce projet.

Merci

**Comment by GSzabados** [comment]
> PS2 : J'écris en français car il semble que nous soyons majoritairement des français à utiliser ce projet.

I actually do not speak French and use it in Poland, because my city installed Itron AnyQuest Cyble meters...

The guy who made the previous project implementing the original code with MQTT support on Raspberry Pi Zero, is from Poland as well.

**Comment by GSzabados** [comment]
> * Avec 433.8615**7** ça semble fonctionner correctement.

The meter has a very large tolerance for the weak up signal. (maybe 25kHz) The code does the search with 0.5kHz steps, the original code used a 2kHz step for same purpose.

**Comment by psykokwak-com** [comment]
Hi all,
I forked this project to make it working on an ESP8266/ESP32 because this is what I mainly use on my projects.
But this code is for test purposes and I have no goal to make a full featured project.
I'm not sure to improve it unless someone send pull requests.
So, to answer to you questions :
- the latest commit I pushed fixes the polling every day at 10.00am (UTC). You are free to change this according to your needs.
- As @GSzabados said, the meter has à very large tolerence on the frequency. The best solution should be to scan the frequencies at a higher step (I recognize that I was a little too precise) to determine the low frequency and the high frequency then to take the frequency in the middle.
- You can manually trigger an update by publishing (any payload you want) on "everblu/cyble/trigger" topic. So create an entity on HA to handle this.
- I did not plan to implement other functions but if it were to be done, I would rather try to do it on an already existing firmware such as tasmota to take advantage of all the advanced functions of the firmware.

**Comment by GSzabados** [comment]
> * determine the low frequency and the high frequency then to take the frequency in the middle.

I did run my device with either 2 or 2.5kHz steps, before I managed to get it right for my meter the wait time between the first and second messages. I was monitoring with an RTL SDR, so I saw when the meter was replying but it hasn't read the values from the answer correctly did not stop the frequency cycle. The high end causes that the meter replies on a full bandwidth spectrum I believe, otherwise, it just replies around the frequency of the wake up signal. Finding a single frequency is absolutely enough. The original purpose was the same, just hit a right frequency, the tolerance is huge.

**Comment by xekil** [comment]
Thank you for your answers, I will continue in English then :)

**Comment by Patbob86** [comment]
Hi everybody!
Thanks for this project I am working on for a few days, unfortunately without success, as I can't get any answer from my Water Counter. 
I use Arduino IDE and I have setup my parameters (wifi, Mqtt, year and Counter number without the first zeros).
I tried a lot of times to connect and scan using the piece of code to find the right frequency in everblu-meters-esp8266.ino, but absolutely no answers at all..
I tried many times, at small distance from the counter (1 meter, 10 meters....). 
Maybe my Counter is broken ??!

I use a D1 Mini and the CC1101 module is a E07-M1101D-SMA. 
The connections between the M1101 module and the D1 Mini seem ok, because I can monitor the sound of the transmission on a Walky Talky according to the frequency displayed on the terminal during the scan.
I don't have a RTL SDR radio module to listen the spectrum.

Is there a specific setup for the M1101D card?
In the different other projects I could find, there is a different value for the GDO0.. 
Some of them say
#define GDO0 0 //header  11
and other, like psykokwak, say
#define GDO0 5 //header  11 
What is the differences in this setting? I tried both, but nothing better...
Merci pour votre aide!

**Comment by GSzabados** [comment]
> Some of them say
> #define GDO0 0 //header 11
> and other, like psykokwak, say
> #define GDO0 5 //header 11
> What is the differences in this setting? I tried both, but nothing better...

That is telling the Wemos D1 that which GPIO pin is connected to the GDO0 of the CC1101.

Please open a separate issue, state what is the model of your meter and what is the serial debug showing when it is unable to read the meter. And please state as well when did you try to communicate with the meter.

**Comment by Patbob86** [comment]
Hi. Thanks for reply.
Ok I will open an other issue to describe my counter..

> That is telling the Wemos D1 that which GPIO pin is connected to the GDO0 of the CC1101.
> 
Sorry, but I don't understand what you mean..
The GDO0 of the CC1101 (M1101D) is pin 3. 
And it is connected to the Wemos D1Mini to pin D1 as recommended .. so I don't see the meaning of 0 or 5 in the setting  of GD0:
With my wiring, do I put #define GDO0 0 or #define GDO0 5 ?

**Comment by GSzabados** [comment]
> Sorry, but I don't understand what you mean..

Open another issue, and I will explain it there.
